### ISSUE TITLE
Future of ACF-builder

### ISSUE THREAD

**Issue by Levdbas** [StoutLogic/acf-builder#189]
Hi @stevep ,

I see it has been a long time since a last release was done. There are also a few PRs that are probably ready to be merged. 

I am wondering what your plans are for ACF builder. Do you want to continue working on it, are you looking for other maintainers? Would love to know! I myself could maybe lend a hand in maintenance.  

As a long time ACF builder fan, I really hope that we can continue this library into the future.

**Comment by Log1x** [comment]
Also willing to help maintain if needed.

**Comment by michaelw85** [comment]
I haven't done much so far, but willing to pitch in. A good and easy start would be to close some tickets that have been resolved.

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bartkleinreesink** [comment]
Off-topic, but because this thread contains people interested in the future of this project: I've just made this repository public: https://github.com/fabrikage/acf-builder-parser - If anyone wants to contribute, feel free!

On-topic: I'm also willing to jump in.

**Comment by Levdbas** [comment]
> Off-topic, but because this thread contains people interested in the future of this project: I've just made this repository public: https://github.com/fabrikage/acf-builder-parser - If anyone wants to contribute, feel free!
> 
> On-topic: I'm also willing to jump in.

Sounds like an amazing library to convert legacy projects to a new code base, you have my star, will try this when the need arises!

**Comment by bartkleinreesink** [comment]
> Sounds like an amazing library to convert legacy projects to a new code base, you have my star, will try this when the need arises!

Thanks for your support! That's exactly the reason I started working on this. Please note that the library is not feature complete yet (and missing tests), I'm still missing 25 out of 36 (I think) field types, but the framework is there. I'll hopefully be adding them in a timely manner.

**Comment by danlapteacru** [comment]
Also willing to help maintain if needed

**Comment by Levdbas** [comment]
I heard that @Log1x , was invited to maintain this repo. Brandon, if we can lend you a hand with restarting the development on this library, let us know!

**Comment by Log1x** [comment]
Hey! I've been meaning to hop in and get some general clean up done but got busy with the year closing out. Feel free to add me on Discord (Log1x) if you have some ideas for helping out.

**Comment by Levdbas** [comment]
To start with a clean slate, I went through all the tickets (I think) and subdivided them. Most tickets can be closed and this will clean up the repo. To me that sounds like a good starting point. After that we can look into introducing some tests, supporting the new field types, etc.

**Can be closed/stale**

- [ ] https://github.com/StoutLogic/acf-builder/issues/194 (Question)
- [ ] https://github.com/StoutLogic/acf-builder/issues/193 (Can't reproduce)
- [ ] https://github.com/StoutLogic/acf-builder/issues/192 (Not related? Can be overridden)
- [ ] https://github.com/StoutLogic/acf-builder/issues/188 (Question, can be answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/186 (Stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/185 (Already fixed)
- [ ] https://github.com/StoutLogic/acf-builder/issues/184 (Stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/183 (Stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/177 (Answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/169 (Answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/163 (Stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/157 (Stale/question)
- [ ] https://github.com/StoutLogic/acf-builder/issues/154 (fixed)
- [ ] https://github.com/StoutLogic/acf-builder/issues/151 (answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/136 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/135 (answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/132 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/131 (stale/answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/123 (answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/118 (answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/113 (answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/111 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/106 (fixed)
- [ ] https://github.com/StoutLogic/acf-builder/issues/100 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/99 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/92 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/90 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/89 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/87 (fixed)
- [ ] https://github.com/StoutLogic/acf-builder/issues/81 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/78 (stale)
- [ ] https://github.com/StoutLogic/acf-builder/issues/63 (stale/answered)
- [ ] https://github.com/StoutLogic/acf-builder/issues/29 (stale)


**Features**

- [ ] https://github.com/StoutLogic/acf-builder/issues/190
- [ ] https://github.com/StoutLogic/acf-builder/issues/152
- [ ] https://github.com/StoutLogic/acf-builder/issues/146
- [ ] https://github.com/StoutLogic/acf-builder/issues/145 (not sure we want this)
- [ ] https://github.com/StoutLogic/acf-builder/issues/126 (not sure we want this)
- [ ] https://github.com/StoutLogic/acf-builder/issues/121
- [ ] https://github.com/StoutLogic/acf-builder/issues/116
- [ ] https://github.com/StoutLogic/acf-builder/issues/97
- [ ] https://github.com/StoutLogic/acf-builder/issues/93 might be superseded if we implement another codestyle
- [ ] https://github.com/StoutLogic/acf-builder/issues/76
- [ ] https://github.com/StoutLogic/acf-builder/issues/71
- [ ] https://github.com/StoutLogic/acf-builder/issues/62
- [ ] https://github.com/StoutLogic/acf-builder/issues/61
- [ ] https://github.com/StoutLogic/acf-builder/issues/60 (not sure we need this)
- [ ] https://github.com/StoutLogic/acf-builder/issues/37


**Bugs**

- [ ] https://github.com/StoutLogic/acf-builder/issues/165 Maybe?
- [ ] https://github.com/StoutLogic/acf-builder/issues/125
- [ ] https://github.com/StoutLogic/acf-builder/issues/110 Maybe?
- [ ] https://github.com/StoutLogic/acf-builder/issues/96

**Documentation**
- [ ] https://github.com/StoutLogic/acf-builder/issues/109 might be good to document this list
- [ ] https://github.com/StoutLogic/acf-builder/issues/48
- [ ] https://github.com/StoutLogic/acf-builder/issues/42

**Comment by alexsoluweb** [comment]
This repo seems to be abandonned by the owner...

**Comment by Levdbas** [comment]
Hi @alexsoluweb , @Log1x currently has full access to the repo and was willing to take a look at the outstanding PRs although he was struggling to find the time to do so, which I respect. But I hope we can move this forward at some point. I would really like to lend a hand in this as well because I have so many sites running on acf builder that I am really incentivized to keep this maintained into the future.

**Comment by mindfullsilence** [comment]
Very concerned this repo is dead - no movement for several years. Migration away from it is going to be an absolute nightmare. Ooft.

**Comment by Levdbas** [comment]
Hold your horses everyone! @Log1x has merged the first commits in and I've been hard at work at:

- #204
- #203
- #202
- #201
- #200
- #197
- #196
- #195
- #191
